# Copyright (c) 2017 ~ 2025, the original authors individual Inc,
# All rights reserved. Contact us James Wong <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment base configuration. ####
#
spring:
  application:
    name: signaltrading-poc
  profiles:
    include: swagger
    #active: dev
  banner:
    location: classpath:META-INF/banner.txt
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #mvc:
  #  pathmatch:
  #    matching-strategy: /**/swagger-ui/**
  infra:
    context:
      logging:
        enabled: true
    core:
      smart-proxies:
        enabled: false

server:
  port: 8888
  servlet:
    # The spring-cloud-loadbalancer-2.2.6 not support metadata.contextPath
    #contextPath: /
    session:
      timeout: 30m
      cookie:
        name: __st_sid

logging:
  register-shutdown-hook: false
  charset.file: UTF-8
  ## Log levels belonging to this group will take effect synchronously.(TRACE|DEBUG|INFO|WARN|ERROR|FATAL|OFF)
  ## see:https://docs.spring.io/spring-boot/docs/2.6.7/reference/htmlsingle/#features.logging.log-groups
  group:
    config: "org.springframework.boot.context.config"
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
  #file: ## see:org.springframework.boot.logging.LogFile#toString
  #  name: /var/log/${spring.application.name}/${spring.application.name}.log
  pattern:
    #console: '{"level":"%level","traceId":"%X{X-B3-TraceId:-}","spanId":"%X{X-B3-SpanId:-}","thread":"%thread","class":"%logger{40}","message":"%message"}%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } [%-0.12X{principal},%-0.32X{traceId},%-0.8X{spanId}] --- [%t] %-40.40logger{39} : %m%n%wEx'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } [%-0.12X{principal},%-0.32X{traceId},%-0.8X{spanId}] --- [%t] %-40.40logger{39} : %m%n%wEx'
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      clean-history-on-start: false ## Default by false
      max-file-size: 1GB ## Default by 200MB
      max-history: 30 ## Default by 7
      total-size-cap: 100GB ## Default by 10GB
  level:
    root: INFO
    tomcat: INFO
    config: INFO
    ## The built-in log groups:
    ## web(org.springframework.core.codec,org.springframework.http,org.springframework.web,org.springframework.boot.actuate.endpoint.web,org.springframework.boot.web.servlet.ServletContextInitializerBeans)
    ## sql(org.springframework.jdbc.core,org.hibernate.SQL,org.jooq.tools.LoggerListener)
    web: INFO
    sql: INFO
    reactor:
      netty.http.client: INFO
    org:
      springframework: INFO
      apache: INFO
    feign: INFO
    com:
      wl4g.signaltrading: INFO

trading:
  default-exchanges:
    - id: 1
      provider: BINANCE
      name: defaultBinance
      description: "The default Binance Exchange configuration instance."
      configuration:
        mainnet-spot-api-endpoint: https://api.binance.com
        mainnet-spot-ws-endpoint: wss://fstream.binance.com
        mainnet-derivatives-api-endpoint: https://fapi.binance.com
        testnet-spot-api-endpoint: https://testnet.binance.vision
        testnet-spot-ws-endpoint: wss://testnet.binance.vision
        testnet-derivatives-api-endpoint: https://testnet.binancefuture.com
  default-strategies:
    - id: 1
      provider: MJSMA
      name: MJSMA_1
      description: "A MJ-SMA Strategy by HBot/@摸金探长"
      parameters:
        symbol: "ETHUSDT"
        quantity: 0.01
        risk-reward-ratio: 2
        stop-loss-percent: 0.01
        use-ma-filter: true
        ma-periods: 20
        ma-interval: "1m"