[package]
name = "sigbot-logservice"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# Other modules dependencies.
common-telemetry.workspace = true
common-makestruct.workspace = true
sigbot-utils.workspace = true
sigbot-types.workspace = true
sigbot-core.workspace = true
sigbot-messager.workspace = true

# Thirdparty dependencies.
clap.workspace = true
async-trait.workspace = true
serde_json.workspace = true
serde.workspace = true
lazy_static.workspace = true
anyhow.workspace = true
tokio.workspace = true
reqwest = { workspace = true, features = ["json"] }
axum = { workspace = true, features = ["ws"] }
axum-macros.workspace = true
tower.workspace = true
tower-http.workspace = true
futures.workspace = true
dashmap.workspace = true